### PR TITLE
BoardConfig.mk: Fix device encryption

### PR DESCRIPTION
**Pull request by TheComputerGuy96**
Taken from this commit: https://github.com/ghsr/android_device_samsung_galaxys2plus-common/commit/3a4279e929ad7ea1b57aa7aff57b4bab2969a8cd

### CODE REVIEW

**Comment by TheComputerGuy96** [comment]
You'll also need to push this commit to all branches and update TWRP

**Comment by TheComputerGuy96** [comment]
Are you busy?

**Comment by minhng99** [comment]
yes, dev for another device

**Comment by TheComputerGuy96** [comment]
Once you'll fix encryption, @ishantvivek, I will close this pull request

**Comment by TheComputerGuy96** [comment]
Once you'll fix encryption in TWRP, @ishantvivek, I will close this pull request

**Comment by ghost** [comment]
Atleast presently i am not going to build twrp. I will think about it later. Maybe after 3-4 months. 

> > Keep this request open, i don't have any problem with it.

**Comment by TheComputerGuy96** [comment]
Why?

**Comment by ghost** [comment]
> > Busy

**Comment by TheComputerGuy96** [comment]
I've opened another pull request with the same topic, so I'll close this pull request

**Pull request closed without merging**
